import org.w3c.dom.Node;
import org.w3c.dom.bootstrap.DOMImplementationRegistry;
import org.w3c.dom.ls.DOMImplementationLS;
import org.w3c.dom.ls.LSSerializer;
import org.xml.sax.InputSource;

import javax.xml.parsers.DocumentBuilderFactory;
import java.io.StringReader;

public class XmlFormatter {

    public String format(String xml) throws Exception {

        final InputSource src = new InputSource(new StringReader(xml));
        final Node document = DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(src).getDocumentElement();
        final Boolean keepDeclaration = xml.startsWith("<?xml");

        final DOMImplementationRegistry registry = DOMImplementationRegistry.newInstance();
        final DOMImplementationLS impl = (DOMImplementationLS) registry.getDOMImplementation("LS");
        final LSSerializer writer = impl.createLSSerializer();

        writer.getDomConfig().setParameter("format-pretty-print", Boolean.TRUE); // Set this to true if the output needs to be beautified.
        writer.getDomConfig().setParameter("xml-declaration", keepDeclaration); // Set this to true if the declaration is needed to be outputted.

        return writer.writeToString(document).replace("UTF-16", "UTF-8");

    }
    
    
    public static final String defaults = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
        "<GraphicsConfig>\n" +
        "    <MinimumAspectRatio>1.0</MinimumAspectRatio>\n" +
        "    <HDRNode>\n" +
        "        <KeyValue>0.500000</KeyValue>\n" +
        "        <WhiteLevel>0.000000</WhiteLevel>\n" +
        "        <DisplayLumScale>164.000000</DisplayLumScale>\n" +
        "        <HistogramSampleWidth>60.500000</HistogramSampleWidth>\n" +
        "        <ExposureThreshold>1.000000</ExposureThreshold>\n" +
        "        <Percentiles>0.010000,0.540000,0.999000</Percentiles>\n" +
        "        <ExposureType>0</ExposureType>\n" +
        "        <HistogramMode>2</HistogramMode>\n" +
        "        <ManualExposure>0.000000</ManualExposure>\n" +
        "        <ShoulderStrength>0.491000</ShoulderStrength>\n" +
        "        <LinearStrength>0.707000</LinearStrength>\n" +
        "        <LinearAngle>0.704000</LinearAngle>\n" +
        "        <ToeStrength>1.185000</ToeStrength>\n" +
        "        <ToeNumerator>1.377000</ToeNumerator>\n" +
        "        <ToeDenominator>1.976000</ToeDenominator>\n" +
        "        <LinearWhite>5.242000</LinearWhite>\n" +
        "    </HDRNode>\n" +
        "    <HDRNode_Reference>\n" +
        "        <KeyValue>0.500000</KeyValue>\n" +
        "        <WhiteLevel>0.000000</WhiteLevel>\n" +
        "        <DisplayLumScale>164.000000</DisplayLumScale>\n" +
        "        <HistogramSampleWidth>60.500000</HistogramSampleWidth>\n" +
        "        <ExposureThreshold>1.000000</ExposureThreshold>\n" +
        "        <Percentiles>0.010000,0.540000,0.999000</Percentiles>\n" +
        "        <ExposureType>0</ExposureType>\n" +
        "        <HistogramMode>2</HistogramMode>\n" +
        "        <ManualExposure>-0.500000</ManualExposure>\n" +
        "        <ShoulderStrength>0.15000</ShoulderStrength>\n" +
        "        <LinearStrength>0.5000</LinearStrength>\n" +
        "        <LinearAngle>0.1000</LinearAngle>\n" +
        "        <ToeStrength>0.2000</ToeStrength>\n" +
        "        <ToeNumerator>0.02000</ToeNumerator>\n" +
        "        <ToeDenominator>0.3000</ToeDenominator>\n" +
        "        <LinearWhite>11.2000</LinearWhite>\n" +
        "    </HDRNode_Reference>\n" +
        "    <IBL>\n" +
        "        <AmbientIBLEnable>true</AmbientIBLEnable>\n" +
        "        <IrradianceMapName>IrradianceMap</IrradianceMapName>\n" +
        "        <Power>1.000000</Power>\n" +
        "        <Saturation>0.150000</Saturation>\n" +
        "        <Scale>4.000000</Scale>\n" +
        "    </IBL>\n" +
        "    <GUIColour>\n" +
        "        <Default>\n" +
        "            <LocalisationName>Standard</LocalisationName>\n" +
        "            <MatrixRed>		1, 0, 0 </MatrixRed>\n" +
        "            <MatrixGreen>	0, 1, 0 </MatrixGreen>\n" +
        "            <MatrixBlue>	0, 0, 1 </MatrixBlue>\n" +
        "        </Default>\n" +
        "        <RedToBlueTest>\n" +
        "            <LocalisationName>RedToBlueTest</LocalisationName>\n" +
        "            <MatrixRed>		0, 0, 1 </MatrixRed>\n" +
        "            <MatrixGreen>	0, 1, 0 </MatrixGreen>\n" +
        "            <MatrixBlue>	1, 0, 0 </MatrixBlue>\n" +
        "        </RedToBlueTest>\n" +
        "        <DesaturateTest>\n" +
        "            <LocalisationName>DesaturateTest</LocalisationName>\n" +
        "            <MatrixRed>		0.33, 0.33, 0.33 </MatrixRed>\n" +
        "            <MatrixGreen>	0.33, 0.33, 0.33 </MatrixGreen>\n" +
        "            <MatrixBlue>	0.33, 0.33, 0.33 </MatrixBlue>\n" +
        "        </DesaturateTest>\n" +
        "    </GUIColour>\n" +
        "    <SSAO>\n" +
        "        <Off>\n" +
        "            <LocalisationName>$QUALITY_OFF;</LocalisationName>\n" +
        "            <Enabled>false</Enabled>\n" +
        "            <NumDownsamples>1</NumDownsamples>\n" +
        "            <DepthThreshold>0.100000</DepthThreshold>\n" +
        "            <MinWorldFilterSize>1.000000</MinWorldFilterSize>\n" +
        "            <MaxWorldFilterSize>30.000000</MaxWorldFilterSize>\n" +
        "            <MinFilterSize>10.000000</MinFilterSize>\n" +
        "            <MaxFilterSize>100.000000</MaxFilterSize>\n" +
        "            <FilterAdjust>1.000000</FilterAdjust>\n" +
        "            <Scale>0.650000</Scale>\n" +
        "            <Offset>1.000000</Offset>\n" +
        "            <AlchemyIntensity>0.750000</AlchemyIntensity>\n" +
        "            <AlchemyBias>0.006000</AlchemyBias>\n" +
        "            <Curve>2.200000</Curve>\n" +
        "            <BackProjectLerp>0.900000</BackProjectLerp>\n" +
        "            <BackProjectDepthThreshold>0.050000</BackProjectDepthThreshold>\n" +
        "            <BackProjectSSAOThreshold>0.333000</BackProjectSSAOThreshold>\n" +
        "            <AttenuationAdjust>0.200000</AttenuationAdjust>\n" +
        "            <DistanceFadeStart>19000.000000</DistanceFadeStart>\n" +
        "            <DistanceFadeEnd>20000.000000</DistanceFadeEnd>\n" +
        "            <BilateralBlurXYSoftness>1.000000</BilateralBlurXYSoftness>\n" +
        "            <BilateralBlurDepthSoftness>0.400000</BilateralBlurDepthSoftness>\n" +
        "            <NumBlurPasses>1</NumBlurPasses>\n" +
        "            <MaxPrevFrames>3</MaxPrevFrames>\n" +
        "            <Jitter>true</Jitter>\n" +
        "            <AnimateJitter>false</AnimateJitter>\n" +
        "            <RegularSamples>false</RegularSamples>\n" +
        "            <BackProjection>false</BackProjection>\n" +
        "            <ExtraSamples>true</ExtraSamples>\n" +
        "            <ExtraBilateralBlurSamples>true</ExtraBilateralBlurSamples>\n" +
        "            <GaussianBlur>false</GaussianBlur>\n" +
        "            <BilateralBlur>true</BilateralBlur>\n" +
        "            <Dilate>false</Dilate>\n" +
        "            <JitterDepthSamples>false</JitterDepthSamples>\n" +
        "            <UseAlchemyAO>true</UseAlchemyAO>\n" +
        "            <AffectDiffuse>1.000000</AffectDiffuse>\n" +
        "            <AffectSpecular>1.000000</AffectSpecular>\n" +
        "            <VignetteScale>7.000000</VignetteScale>\n" +
        "            <LumLerpScale>0.800000</LumLerpScale>\n" +
        "            <LumLerpOffset>0.000000</LumLerpOffset>\n" +
        "        </Off>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <Enabled>true</Enabled>\n" +
        "            <NumDownsamples>1</NumDownsamples>\n" +
        "            <DepthThreshold>0.522</DepthThreshold>\n" +
        "            <MinWorldFilterSize>0.489</MinWorldFilterSize>\n" +
        "            <MaxWorldFilterSize>0.451</MaxWorldFilterSize>\n" +
        "            <MinFilterSize>13.204</MinFilterSize>\n" +
        "            <MaxFilterSize>100.000000</MaxFilterSize>\n" +
        "            <FilterAdjust>1.000000</FilterAdjust>\n" +
        "            <FilterAspect>5.000000</FilterAspect>\n" +
        "            <Scale>0.650000</Scale>\n" +
        "            <Offset>1.000000</Offset>\n" +
        "            <AlchemyIntensity>1.055</AlchemyIntensity>\n" +
        "            <AlchemyBias>0.017</AlchemyBias>\n" +
        "            <Curve>1.178</Curve>\n" +
        "            <BackProjectLerp>0.900000</BackProjectLerp>\n" +
        "            <BackProjectDepthThreshold>0.050000</BackProjectDepthThreshold>\n" +
        "            <BackProjectSSAOThreshold>0.333000</BackProjectSSAOThreshold>\n" +
        "            <AttenuationAdjust>0.200000</AttenuationAdjust>\n" +
        "            <DistanceFadeStart>100.0</DistanceFadeStart>\n" +
        "            <DistanceFadeEnd>320.0</DistanceFadeEnd>\n" +
        "            <BilateralBlurXYSoftness>1.000000</BilateralBlurXYSoftness>\n" +
        "            <BilateralBlurDepthSoftness>0.400000</BilateralBlurDepthSoftness>\n" +
        "            <NumBlurPasses>1</NumBlurPasses>\n" +
        "            <MaxPrevFrames>3</MaxPrevFrames>\n" +
        "            <Jitter>true</Jitter>\n" +
        "            <AnimateJitter>false</AnimateJitter>\n" +
        "            <RegularSamples>false</RegularSamples>\n" +
        "            <BackProjection>false</BackProjection>\n" +
        "            <ExtraSamples>true</ExtraSamples>\n" +
        "            <ExtraBilateralBlurSamples>true</ExtraBilateralBlurSamples>\n" +
        "            <GaussianBlur>false</GaussianBlur>\n" +
        "            <BilateralBlur>true</BilateralBlur>\n" +
        "            <Dilate>false</Dilate>\n" +
        "            <JitterDepthSamples>false</JitterDepthSamples>\n" +
        "            <UseAlchemyAO>true</UseAlchemyAO>\n" +
        "            <AffectDiffuse>1.000000</AffectDiffuse>\n" +
        "            <AffectSpecular>1.000000</AffectSpecular>\n" +
        "            <VignetteScale>7.000000</VignetteScale>\n" +
        "            <LumLerpScale>0.800000</LumLerpScale>\n" +
        "            <LumLerpOffset>0.000000</LumLerpOffset>\n" +
        "        </High>\n" +
        "    </SSAO>\n" +
        "    <LightCones>\n" +
        "        <Off>\n" +
        "            <LocalisationName>$QUALITY_OFF;</LocalisationName>\n" +
        "            <Enabled>false</Enabled>\n" +
        "            <Volumetric>false</Volumetric>\n" +
        "        </Off>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <Enabled>true</Enabled>\n" +
        "            <Volumetric>false</Volumetric>\n" +
        "        </Low>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <Enabled>true</Enabled>\n" +
        "            <Volumetric>true</Volumetric>\n" +
        "        </High>\n" +
        "    </LightCones>\n" +
        "    <LensFlares>\n" +
        "        <Off>\n" +
        "            <LocalisationName>$QUALITY_OFF;</LocalisationName>\n" +
        "            <Enabled>false</Enabled>\n" +
        "            <QualityIndex>0</QualityIndex>\n" +
        "            <ImportanceThreshold>2</ImportanceThreshold>\n" +
        "        </Off>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <Enabled>true</Enabled>\n" +
        "            <QualityIndex>0</QualityIndex>\n" +
        "            <ImportanceThreshold>2</ImportanceThreshold>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <Enabled>true</Enabled>\n" +
        "            <QualityIndex>1</QualityIndex>\n" +
        "            <ImportanceThreshold>1</ImportanceThreshold>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <Enabled>true</Enabled>\n" +
        "            <QualityIndex>2</QualityIndex>\n" +
        "            <ImportanceThreshold>0</ImportanceThreshold>\n" +
        "        </High>\n" +
        "    </LensFlares>\n" +
        "    <Shadows_Low>\n" +
        "        <SliceSize>1024</SliceSize>\n" +
        "        <NumFrustums>1</NumFrustums>\n" +
        "        <Frustum0>\n" +
        "            <EndDistance>2100.000000</EndDistance>\n" +
        "            <ShaderBias>0.0004</ShaderBias>\n" +
        "            <ShaderSlopeBias>0.004</ShaderSlopeBias>\n" +
        "            <DepthBias>0.001</DepthBias>\n" +
        "            <DepthSlopeBias>1.5</DepthSlopeBias>\n" +
        "            <FilterKernelSize>1.000000</FilterKernelSize>\n" +
        "            <TexelStability>1</TexelStability>\n" +
        "        </Frustum0>\n" +
        "    </Shadows_Low>\n" +
        "    <Shadows_Medium>\n" +
        "        <SliceSize>1024</SliceSize>\n" +
        "        <NumFrustums>2</NumFrustums>\n" +
        "        <FilterQuality>1</FilterQuality>\n" +
        "        <AdaptiveCascades>true</AdaptiveCascades>\n" +
        "        <AdaptivePadding>50.0</AdaptivePadding>\n" +
        "        <AdaptiveQuantum>0.05</AdaptiveQuantum>\n" +
        "        <AdaptiveMinRatio>0.25</AdaptiveMinRatio>\n" +
        "        <AdaptiveTimeStep>0.2</AdaptiveTimeStep>\n" +
        "        <Frustum0>\n" +
        "            <EndDistance>4.000000</EndDistance>\n" +
        "            <ShaderBias>0.0002</ShaderBias>\n" +
        "            <ShaderSlopeBias>0.0002</ShaderSlopeBias>\n" +
        "            <DepthBias>0.0001</DepthBias>\n" +
        "            <DepthSlopeBias>1.5</DepthSlopeBias>\n" +
        "            <FilterKernelSize>1.000000</FilterKernelSize>\n" +
        "        </Frustum0>\n" +
        "        <Frustum1>\n" +
        "            <EndDistance>2100.000000</EndDistance>\n" +
        "            <ShaderBias>0.0004</ShaderBias>\n" +
        "            <ShaderSlopeBias>0.004</ShaderSlopeBias>\n" +
        "            <DepthBias>0.001</DepthBias>\n" +
        "            <DepthSlopeBias>1.5</DepthSlopeBias>\n" +
        "            <FilterKernelSize>1.000000</FilterKernelSize>\n" +
        "            <TexelStability>1</TexelStability>\n" +
        "        </Frustum1>\n" +
        "    </Shadows_Medium>\n" +
        "    <Shadows_High>\n" +
        "        <SliceSize>1536</SliceSize>\n" +
        "        <NumFrustums>4</NumFrustums>\n" +
        "        <FilterQuality>2</FilterQuality>\n" +
        "        <Fade>0.01</Fade>\n" +
        "        <CrossFadeCascades>true</CrossFadeCascades>\n" +
        "        <AdaptiveCascades>true</AdaptiveCascades>\n" +
        "        <AdaptivePadding>150.0</AdaptivePadding>\n" +
        "        <AdaptiveQuantum>0.02</AdaptiveQuantum>\n" +
        "        <AdaptiveMinRatio>0.1</AdaptiveMinRatio>\n" +
        "        <AdaptiveTimeStep>0.2</AdaptiveTimeStep>\n" +
        "        <Frustum0>\n" +
        "            <EndDistance>5.000000</EndDistance>\n" +
        "            <ShaderBias>0.0003</ShaderBias>\n" +
        "            <ShaderSlopeBias>0.0003</ShaderSlopeBias>\n" +
        "            <DepthBias>0.0003</DepthBias>\n" +
        "            <DepthSlopeBias>2.5</DepthSlopeBias>\n" +
        "            <FilterKernelSize>2.5</FilterKernelSize>\n" +
        "        </Frustum0>\n" +
        "        <Frustum1>\n" +
        "            <EndDistance>800.000000</EndDistance>\n" +
        "            <ShaderBias>0.0003</ShaderBias>\n" +
        "            <ShaderSlopeBias>0.003</ShaderSlopeBias>\n" +
        "            <DepthBias>0.001</DepthBias>\n" +
        "            <DepthSlopeBias>2.5</DepthSlopeBias>\n" +
        "            <FilterKernelSize>2.5</FilterKernelSize>\n" +
        "            <TexelStability>0</TexelStability>\n" +
        "        </Frustum1>\n" +
        "        <Frustum2>\n" +
        "            <EndDistance>3200.000000</EndDistance>\n" +
        "            <ShaderBias>0.0003</ShaderBias>\n" +
        "            <ShaderSlopeBias>0.003</ShaderSlopeBias>\n" +
        "            <DepthBias>0.001</DepthBias>\n" +
        "            <DepthSlopeBias>1.5</DepthSlopeBias>\n" +
        "            <FilterKernelSize>2.5</FilterKernelSize>\n" +
        "            <TexelStability>0</TexelStability>\n" +
        "        </Frustum2>\n" +
        "        <Frustum3>\n" +
        "            <EndDistance>12800.000000</EndDistance>\n" +
        "            <ShaderBias>0.0003</ShaderBias>\n" +
        "            <ShaderSlopeBias>0.003</ShaderSlopeBias>\n" +
        "            <DepthBias>0.001</DepthBias>\n" +
        "            <DepthSlopeBias>1.5</DepthSlopeBias>\n" +
        "            <FilterKernelSize>2.5</FilterKernelSize>\n" +
        "            <TexelStability>0</TexelStability>\n" +
        "        </Frustum3>\n" +
        "        <NumSpotShadows>6</NumSpotShadows>\n" +
        "        <SpotFilterQuality>1</SpotFilterQuality>\n" +
        "    </Shadows_High>\n" +
        "    <Planets>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <TextureSize>512</TextureSize>\n" +
        "            <AtmosphereSteps>4</AtmosphereSteps>\n" +
        "            <CloudsEnabled>true</CloudsEnabled>\n" +
        "            <WorkPerFrame>128</WorkPerFrame>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <TextureSize>1024</TextureSize>\n" +
        "            <AtmosphereSteps>5</AtmosphereSteps>\n" +
        "            <CloudsEnabled>true</CloudsEnabled>\n" +
        "            <WorkPerFrame>192</WorkPerFrame>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <TextureSize>2560</TextureSize>\n" +
        "            <AtmosphereSteps>6</AtmosphereSteps>\n" +
        "            <CloudsEnabled>true</CloudsEnabled>\n" +
        "            <WorkPerFrame>256</WorkPerFrame>\n" +
        "        </High>\n" +
        "    </Planets>\n" +
        "    <GalaxyBackground>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <TextureSize>512</TextureSize>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <TextureSize>1024</TextureSize>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <TextureSize>2048</TextureSize>\n" +
        "        </High>\n" +
        "    </GalaxyBackground>\n" +
        "    <Bloom>\n" +
        "        <Off>\n" +
        "            <LocalisationName>$QUALITY_OFF;</LocalisationName>\n" +
        "            <Method>Off</Method>\n" +
        "        </Off>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <Method>HighPassCount</Method>\n" +
        "            <MinThreshold>3.940000</MinThreshold>\n" +
        "            <MaxThreshold>200.000000</MaxThreshold>\n" +
        "            <GlareWeight0>0.800000</GlareWeight0>\n" +
        "            <GlareWeight1>0.700000</GlareWeight1>\n" +
        "            <GlareWeight2>0.800000</GlareWeight2>\n" +
        "            <GlareWeight3>0.250000</GlareWeight3>\n" +
        "            <GlareWeight4>0.415000</GlareWeight4>\n" +
        "            <GlareScale>7.600000</GlareScale>\n" +
        "            <LumBasedThreshold>false</LumBasedThreshold>\n" +
        "        </High>\n" +
        "    </Bloom>\n" +
        "    <Envmap>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <TextureSize>256</TextureSize>\n" +
        "            <NumMips>8</NumMips>\n" +
        "        </Low>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <TextureSize>256</TextureSize>\n" +
        "            <NumMips>8</NumMips>\n" +
        "        </High>\n" +
        "    </Envmap>\n" +
        "    <Materials>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <MaterialQualityLevel>0</MaterialQualityLevel>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <MaterialQualityLevel>1</MaterialQualityLevel>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <MaterialQualityLevel>2</MaterialQualityLevel>\n" +
        "        </High>\n" +
        "        <Ultra>\n" +
        "            <LocalisationName>$QUALITY_ULTRA;</LocalisationName>\n" +
        "            <MaterialQualityLevel>3</MaterialQualityLevel>\n" +
        "        </Ultra>\n" +
        "    </Materials>\n" +
        "    <Environment>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <Item>\n" +
        "                <Feature>GalaxyBackground</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Planets</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>DamageDecals</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <Item>\n" +
        "                <Feature>GalaxyBackground</Feature>\n" +
        "                <QualitySetting>1</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Planets</Feature>\n" +
        "                <QualitySetting>1</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>DamageDecals</Feature>\n" +
        "                <QualitySetting>1</QualitySetting>\n" +
        "            </Item>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <Item>\n" +
        "                <Feature>GalaxyBackground</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Planets</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>DamageDecals</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "        </High>\n" +
        "    </Environment>\n" +
        "    <GalaxyMap>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <NebulasCount>10</NebulasCount>\n" +
        "            <NebulasInBackgroundCount>40</NebulasInBackgroundCount>\n" +
        "            <LowResNebulasCount>16</LowResNebulasCount>\n" +
        "            <HighResNebulasCount>1</HighResNebulasCount>\n" +
        "            <LowResNebulaDimensions>64</LowResNebulaDimensions>\n" +
        "            <HighResNebulaDimensions>256</HighResNebulaDimensions>\n" +
        "            <LowResSamplesCount>25</LowResSamplesCount>\n" +
        "            <HighResSamplesCount>128</HighResSamplesCount>\n" +
        "            <MilkyWayInstancesCount>8000</MilkyWayInstancesCount>\n" +
        "            <LocalDustBrightness>0.13</LocalDustBrightness>\n" +
        "            <MilkywayInstancesBrightness>1.5</MilkywayInstancesBrightness>\n" +
        "            <MilkywayInstancesSize>1.3</MilkywayInstancesSize>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <NebulasCount>20</NebulasCount>\n" +
        "            <NebulasInBackgroundCount>40</NebulasInBackgroundCount>\n" +
        "            <LowResNebulasCount>16</LowResNebulasCount>\n" +
        "            <HighResNebulasCount>1</HighResNebulasCount>\n" +
        "            <LowResNebulaDimensions>64</LowResNebulaDimensions>\n" +
        "            <HighResNebulaDimensions>256</HighResNebulaDimensions>\n" +
        "            <LowResSamplesCount>30</LowResSamplesCount>\n" +
        "            <HighResSamplesCount>110</HighResSamplesCount>\n" +
        "            <MilkyWayInstancesCount>12000</MilkyWayInstancesCount>\n" +
        "            <LocalDustBrightness>0.033</LocalDustBrightness>\n" +
        "            <MilkywayInstancesBrightness>1.3</MilkywayInstancesBrightness>\n" +
        "            <MilkywayInstancesSize>1.15</MilkywayInstancesSize>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <NebulasCount>30</NebulasCount>\n" +
        "            <NebulasInBackgroundCount>40</NebulasInBackgroundCount>\n" +
        "            <LowResNebulasCount>16</LowResNebulasCount>\n" +
        "            <HighResNebulasCount>1</HighResNebulasCount>\n" +
        "            <LowResNebulaDimensions>64</LowResNebulaDimensions>\n" +
        "            <HighResNebulaDimensions>256</HighResNebulaDimensions>\n" +
        "            <LowResSamplesCount>35</LowResSamplesCount>\n" +
        "            <HighResSamplesCount>138</HighResSamplesCount>\n" +
        "            <MilkyWayInstancesCount>16000</MilkyWayInstancesCount>\n" +
        "            <LocalDustBrightness>0.0</LocalDustBrightness>\n" +
        "            <MilkywayInstancesBrightness>1.0</MilkywayInstancesBrightness>\n" +
        "            <MilkywayInstancesSize>1.0</MilkywayInstancesSize>\n" +
        "        </High>\n" +
        "    </GalaxyMap>\n" +
        "    <FX>\n" +
        "        <Off>\n" +
        "            <LocalisationName>$QUALITY_OFF;</LocalisationName>\n" +
        "            <Item>\n" +
        "                <Feature>LightCones</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>LensFlares</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Debris</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>ParticleEffects</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Trails</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Beams</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "        </Off>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <Item>\n" +
        "                <Feature>LightCones</Feature>\n" +
        "                <QualitySetting>1</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>LensFlares</Feature>\n" +
        "                <QualitySetting>1</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Debris</Feature>\n" +
        "                <QualitySetting>1</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>ParticleEffects</Feature>\n" +
        "                <QualitySetting>0</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Trails</Feature>\n" +
        "                <QualitySetting>1</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Beams</Feature>\n" +
        "                <QualitySetting>1</QualitySetting>\n" +
        "            </Item>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <Item>\n" +
        "                <Feature>LightCones</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>LensFlares</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Debris</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>ParticleEffects</Feature>\n" +
        "                <QualitySetting>1</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Trails</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Beams</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <Item>\n" +
        "                <Feature>LightCones</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>LensFlares</Feature>\n" +
        "                <QualitySetting>3</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Debris</Feature>\n" +
        "                <QualitySetting>3</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>ParticleEffects</Feature>\n" +
        "                <QualitySetting>2</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Trails</Feature>\n" +
        "                <QualitySetting>3</QualitySetting>\n" +
        "            </Item>\n" +
        "            <Item>\n" +
        "                <Feature>Beams</Feature>\n" +
        "                <QualitySetting>3</QualitySetting>\n" +
        "            </Item>\n" +
        "        </High>\n" +
        "    </FX>\n" +
        "    <Debris>\n" +
        "        <Off>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <DebrisLimit>100</DebrisLimit>\n" +
        "        </Off>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <DebrisLimit>200</DebrisLimit>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <DebrisLimit>1000</DebrisLimit>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_ULTRA;</LocalisationName>\n" +
        "            <DebrisLimit>3000</DebrisLimit>\n" +
        "        </High>\n" +
        "    </Debris>\n" +
        "    <DamageDecals>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <SingleDecalReceiversCount>3</SingleDecalReceiversCount>\n" +
        "            <TrailDecalReceiversCount>3</TrailDecalReceiversCount>\n" +
        "            <Enabled>true</Enabled>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <SingleDecalReceiversCount>4</SingleDecalReceiversCount>\n" +
        "            <TrailDecalReceiversCount>4</TrailDecalReceiversCount>\n" +
        "            <Enabled>true</Enabled>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <SingleDecalReceiversCount>5</SingleDecalReceiversCount>\n" +
        "            <TrailDecalReceiversCount>5</TrailDecalReceiversCount>\n" +
        "            <Enabled>true</Enabled>\n" +
        "        </High>\n" +
        "    </DamageDecals>\n" +
        "    <ParticleEffects>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <AllowedEffects>\n" +
        "                <Item>P1</Item>\n" +
        "            </AllowedEffects>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <AllowedEffects>\n" +
        "                <Item>P1</Item>\n" +
        "                <Item>P2</Item>\n" +
        "            </AllowedEffects>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <AllowedEffects>\n" +
        "                <Item>P1</Item>\n" +
        "                <Item>P2</Item>\n" +
        "                <Item>P3</Item>\n" +
        "            </AllowedEffects>\n" +
        "        </High>\n" +
        "    </ParticleEffects>\n" +
        "    <Trails>\n" +
        "        <Off>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <EnableStarTrails>0</EnableStarTrails>\n" +
        "            <EnableEngineTrails>0</EnableEngineTrails>\n" +
        "            <EnableWeaponTrails>1</EnableWeaponTrails>\n" +
        "            <EnableHyperspaceTrails>1</EnableHyperspaceTrails>\n" +
        "            <LifetimeMultiplier>0.25</LifetimeMultiplier>\n" +
        "            <RayMarchSteps>2</RayMarchSteps>\n" +
        "            <Level_0>\n" +
        "                <Distance>1500.0</Distance>\n" +
        "                <UpdateRateRcp>8</UpdateRateRcp>\n" +
        "            </Level_0>\n" +
        "            <Level_1>\n" +
        "                <Distance>2500.0</Distance>\n" +
        "                <UpdateRateRcp>10</UpdateRateRcp>\n" +
        "            </Level_1>\n" +
        "            <Level_2>\n" +
        "                <Distance>3500.0</Distance>\n" +
        "                <UpdateRateRcp>14</UpdateRateRcp>\n" +
        "            </Level_2>\n" +
        "        </Off>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <EnableStarTrails>1</EnableStarTrails>\n" +
        "            <EnableEngineTrails>1</EnableEngineTrails>\n" +
        "            <EnableWeaponTrails>1</EnableWeaponTrails>\n" +
        "            <EnableHyperspaceTrails>1</EnableHyperspaceTrails>\n" +
        "            <LifetimeMultiplier>0.5</LifetimeMultiplier>\n" +
        "            <RayMarchSteps>4</RayMarchSteps>\n" +
        "            <Level_0>\n" +
        "                <Distance>1500.0</Distance>\n" +
        "                <UpdateRateRcp>6</UpdateRateRcp>\n" +
        "            </Level_0>\n" +
        "            <Level_1>\n" +
        "                <Distance>2500.0</Distance>\n" +
        "                <UpdateRateRcp>8</UpdateRateRcp>\n" +
        "            </Level_1>\n" +
        "            <Level_2>\n" +
        "                <Distance>3500.0</Distance>\n" +
        "                <UpdateRateRcp>12</UpdateRateRcp>\n" +
        "            </Level_2>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <EnableStarTrails>1</EnableStarTrails>\n" +
        "            <EnableEngineTrails>1</EnableEngineTrails>\n" +
        "            <EnableWeaponTrails>1</EnableWeaponTrails>\n" +
        "            <EnableHyperspaceTrails>1</EnableHyperspaceTrails>\n" +
        "            <LifetimeMultiplier>1.0</LifetimeMultiplier>\n" +
        "            <RayMarchSteps>4</RayMarchSteps>\n" +
        "            <Level_0>\n" +
        "                <Distance>1500.0</Distance>\n" +
        "                <UpdateRateRcp>4</UpdateRateRcp>\n" +
        "            </Level_0>\n" +
        "            <Level_1>\n" +
        "                <Distance>2500.0</Distance>\n" +
        "                <UpdateRateRcp>6</UpdateRateRcp>\n" +
        "            </Level_1>\n" +
        "            <Level_2>\n" +
        "                <Distance>3500.0</Distance>\n" +
        "                <UpdateRateRcp>10</UpdateRateRcp>\n" +
        "            </Level_2>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_ULTRA;</LocalisationName>\n" +
        "            <EnableStarTrails>1</EnableStarTrails>\n" +
        "            <EnableEngineTrails>1</EnableEngineTrails>\n" +
        "            <EnableWeaponTrails>1</EnableWeaponTrails>\n" +
        "            <EnableHyperspaceTrails>1</EnableHyperspaceTrails>\n" +
        "            <LifetimeMultiplier>1.0</LifetimeMultiplier>\n" +
        "            <RayMarchSteps>8</RayMarchSteps>\n" +
        "            <Level_0>\n" +
        "                <Distance>1500.0</Distance>\n" +
        "                <UpdateRateRcp>2</UpdateRateRcp>\n" +
        "            </Level_0>\n" +
        "            <Level_1>\n" +
        "                <Distance>2500.0</Distance>\n" +
        "                <UpdateRateRcp>4</UpdateRateRcp>\n" +
        "            </Level_1>\n" +
        "            <Level_2>\n" +
        "                <Distance>3500.0</Distance>\n" +
        "                <UpdateRateRcp>8</UpdateRateRcp>\n" +
        "            </Level_2>\n" +
        "        </High>\n" +
        "    </Trails>\n" +
        "    <Beams>\n" +
        "        <Off>\n" +
        "            <LocalisationName>$QUALITY_LOW;</LocalisationName>\n" +
        "            <EnableBeamLights>0</EnableBeamLights>\n" +
        "        </Off>\n" +
        "        <Low>\n" +
        "            <LocalisationName>$QUALITY_MEDIUM;</LocalisationName>\n" +
        "            <EnableBeamLights>0</EnableBeamLights>\n" +
        "        </Low>\n" +
        "        <Medium>\n" +
        "            <LocalisationName>$QUALITY_HIGH;</LocalisationName>\n" +
        "            <EnableBeamLights>1</EnableBeamLights>\n" +
        "        </Medium>\n" +
        "        <High>\n" +
        "            <LocalisationName>$QUALITY_ULTRA;</LocalisationName>\n" +
        "            <EnableBeamLights>1</EnableBeamLights>\n" +
        "        </High>\n" +
        "    </Beams>\n" +
        "</GraphicsConfig>";
}